facebook_api:
    version: v13.0
    business_id: 807747622918576
    app_id: 310868345762440
    app_secret: ecf44d2384d6da7c1c3572c38ef728f3
    user_access_token: EAAEau61SMogBAKXf5ZCiYZC2WkmfCAkZCEz1cQoZBTgg4AdxRAAmG5ZAcH8hrSEsXPDZBPFodOdKr7s49i4ZBecZAZBnnV86z5HMCZAaYp1s2WoUj5P5PzYXTX6Gao2awkZBBudMZBubxwlG3UeRUZBCsBTb5GCeHbAsJFdf0Bal6Rpou4ORNt56cpVpK
    
somin_api:
    authorization:
        version: v1
        username: developer
        password: 12345
    colors: 
        version: v2
    concepts:
        version: v3
